// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjod7bv4_CIx1mW5FtzZPwSci_XS95XIk',
    appId: '1:312134928781:web:e6dbbc7f3570d390b655c4',
    messagingSenderId: '312134928781',
    projectId: 'cptmn-dd372',
    authDomain: 'cptmn-dd372.firebaseapp.com',
    storageBucket: 'cptmn-dd372.firebasestorage.app',
    measurementId: 'G-7EZHKV0SCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw9oMIMPNwHnjLMT31ktd28fRyW_CpIsE',
    appId: '1:312134928781:android:e9cdd49a61fda792b655c4',
    messagingSenderId: '312134928781',
    projectId: 'cptmn-dd372',
    storageBucket: 'cptmn-dd372.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR5-6sApTtstrbl3pmL7cojvgXye7kgZk',
    appId: '1:312134928781:ios:80d1f0cff60ccdb1b655c4',
    messagingSenderId: '312134928781',
    projectId: 'cptmn-dd372',
    storageBucket: 'cptmn-dd372.firebasestorage.app',
    iosBundleId: 'com.chennapatanam.chennapatanam',
  );
}
